name: Feature Request
description: Suggest an idea or enhancement for AI-CORE
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - API Gateway
        - MCP Manager
        - Intent Parser
        - Frontend UI
        - Database
        - Authentication
        - Documentation
        - Development Tools
        - CI/CD
        - Infrastructure
        - Multiple Components
        - New Component
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my work)
        - High (Would significantly improve my workflow)
        - Medium (Nice to have)
        - Low (Minor enhancement)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (Few lines of code)
        - Medium (Moderate development effort)
        - Complex (Significant development effort)
        - Very Complex (Major architectural changes)
        - Unknown
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be beneficial.
      placeholder: |
        1. As a developer, I want to...
        2. As a user, I want to...
        3. As an administrator, I want to...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Feature does X
        - [ ] Feature handles Y
        - [ ] Documentation is updated
        - [ ] Tests are added
    validations:
      required: false

  - type: textarea
    id: technical-considerations
    attributes:
      label: Technical Considerations
      description: Any technical details, constraints, or considerations for implementation.
      placeholder: |
        - Performance requirements
        - Security considerations
        - Compatibility requirements
        - Dependencies
    validations:
      required: false

  - type: input
    id: target-version
    attributes:
      label: Target Version
      description: Which version or milestone should this feature target?
      placeholder: "e.g., v1.1.0, Q1 2025, or 'next release'"
    validations:
      required: false

  - type: textarea
    id: mockups-wireframes
    attributes:
      label: Mockups/Wireframes
      description: If applicable, add mockups, wireframes, or visual representations of the feature.
      placeholder: |
        - Upload images by dragging and dropping
        - Or provide links to design files
        - ASCII art for simple layouts
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: |
        - Links to similar implementations
        - Research or references
        - Community feedback
        - Business justification
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear description of the feature
          required: true
        - label: I understand this is a suggestion and may not be implemented immediately
          required: true
        - label: I am willing to contribute to the implementation if possible
          required: false
