# Prometheus Configuration for AI-PLATFORM Platform
# Modern 2025 monitoring setup with comprehensive service discovery

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'AI-PLATFORM-dev'
    environment: 'development'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Rules files
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # AI-PLATFORM API Gateway
  - job_name: 'AI-PLATFORM-api-gateway'
    static_configs:
      - targets: ['api-gateway:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    basic_auth:
      username: 'prometheus'
      password: 'metrics_password'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: api-gateway:9090

  # PostgreSQL Database Metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+):\d+'
        replacement: '${1}'

  # MongoDB Metrics
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # ClickHouse Metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    scrape_interval: 30s
    metrics_path: /metrics
    basic_auth:
      username: 'ai_core_clickhouse'
      password: 'ai_core_clickhouse_password'

  # Temporal.io Workflow Engine
  - job_name: 'temporal'
    static_configs:
      - targets: ['temporal:7233']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node.js Frontend Metrics (if enabled)
  - job_name: 'frontend-ui'
    static_configs:
      - targets: ['frontend-ui:3001']  # Assuming metrics endpoint on 3001
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Traefik Reverse Proxy
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Docker Container Metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # Kafka Metrics (if using Kafka)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9308']  # JMX exporter port
    scrape_interval: 30s
    metrics_path: /metrics

  # MinIO S3 Storage Metrics
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s
    metrics_path: /minio/v2/metrics/cluster
    bearer_token_file: /etc/prometheus/minio_token

  # Jaeger Tracing Metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s
    metrics_path: /metrics

  # Loki Log Aggregation Metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana Dashboard Metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker Service Discovery (for dynamic services)
  - job_name: 'docker-services'
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: services
        port: 9090
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: job
      - source_labels: [__meta_dockerswarm_service_label_prometheus_port]
        target_label: __address__
        regex: '(.+)'
        replacement: '${1}:9090'

# Remote write configuration (for long-term storage)
remote_write:
  - url: "http://cortex:9009/api/prom/push"
    queue_config:
      max_samples_per_send: 10000
      max_shards: 200
      capacity: 100000

# Storage configuration
storage:
  tsdb:
    path: /prometheus/
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true

# Web configuration
web:
  enable-lifecycle: true
  enable-admin-api: true
  page-title: "AI-PLATFORM Prometheus"
  external-url: http://localhost:9090

# Log configuration
log:
  level: info
  format: json
